[2023-02-24T21:07:14.885+0530] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: nsdlfpi_and_rupee.send_email scheduled__2023-02-23T00:00:00+00:00 [queued]>
[2023-02-24T21:07:14.894+0530] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: nsdlfpi_and_rupee.send_email scheduled__2023-02-23T00:00:00+00:00 [queued]>
[2023-02-24T21:07:14.894+0530] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-24T21:07:14.894+0530] {taskinstance.py:1284} INFO - Starting attempt 1 of 4
[2023-02-24T21:07:14.894+0530] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-24T21:07:14.917+0530] {taskinstance.py:1304} INFO - Executing <Task(EmailOperator): send_email> on 2023-02-23 00:00:00+00:00
[2023-02-24T21:07:14.923+0530] {standard_task_runner.py:55} INFO - Started process 7825 to run task
[2023-02-24T21:07:14.926+0530] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'nsdlfpi_and_rupee', 'send_email', 'scheduled__2023-02-23T00:00:00+00:00', '--job-id', '4735', '--raw', '--subdir', 'DAGS_FOLDER/nsdl_and_rupee.py', '--cfg-path', '/tmp/tmpzbsnyj2_']
[2023-02-24T21:07:14.927+0530] {standard_task_runner.py:83} INFO - Job 4735: Subtask send_email
[2023-02-24T21:07:14.988+0530] {task_command.py:389} INFO - Running <TaskInstance: nsdlfpi_and_rupee.send_email scheduled__2023-02-23T00:00:00+00:00 [running]> on host DESKTOP-SQIOQPD.
[2023-02-24T21:07:15.068+0530] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=nikheleshbhattacharyya@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=nsdlfpi_and_rupee
AIRFLOW_CTX_TASK_ID=send_email
AIRFLOW_CTX_EXECUTION_DATE=2023-02-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-23T00:00:00+00:00
[2023-02-24T21:07:15.093+0530] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.8/dist-packages/airflow/utils/email.py:120 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2023-02-24T21:07:15.093+0530] {email.py:229} INFO - Email alerting: attempt 1
[2023-02-24T21:07:43.249+0530] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/email.py", line 77, in execute
    send_email(
  File "/usr/local/lib/python3.8/dist-packages/airflow/utils/email.py", line 59, in send_email
    return backend(
  File "/usr/local/lib/python3.8/dist-packages/airflow/utils/email.py", line 120, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/usr/local/lib/python3.8/dist-packages/airflow/utils/email.py", line 231, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/usr/local/lib/python3.8/dist-packages/airflow/utils/email.py", line 265, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable
[2023-02-24T21:07:43.272+0530] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=nsdlfpi_and_rupee, task_id=send_email, execution_date=20230223T000000, start_date=20230224T153714, end_date=20230224T153743
[2023-02-24T21:07:43.290+0530] {standard_task_runner.py:100} ERROR - Failed to execute job 4735 for task send_email ([Errno 101] Network is unreachable; 7825)
[2023-02-24T21:07:43.337+0530] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-24T21:07:43.356+0530] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
