[2023-02-03T11:36:08.604+0530] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Monthly.extract manual__2023-02-03T06:05:58.663215+00:00 [queued]>
[2023-02-03T11:36:08.618+0530] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Monthly.extract manual__2023-02-03T06:05:58.663215+00:00 [queued]>
[2023-02-03T11:36:08.619+0530] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-03T11:36:08.619+0530] {taskinstance.py:1284} INFO - Starting attempt 1 of 4
[2023-02-03T11:36:08.619+0530] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-03T11:36:08.643+0530] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract> on 2023-02-03 06:05:58.663215+00:00
[2023-02-03T11:36:08.653+0530] {standard_task_runner.py:55} INFO - Started process 20037 to run task
[2023-02-03T11:36:08.656+0530] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'Monthly', 'extract', 'manual__2023-02-03T06:05:58.663215+00:00', '--job-id', '3922', '--raw', '--subdir', 'DAGS_FOLDER/Monthly.py', '--cfg-path', '/tmp/tmpd_0kduz6']
[2023-02-03T11:36:08.658+0530] {standard_task_runner.py:83} INFO - Job 3922: Subtask extract
[2023-02-03T11:36:08.753+0530] {task_command.py:389} INFO - Running <TaskInstance: Monthly.extract manual__2023-02-03T06:05:58.663215+00:00 [running]> on host DESKTOP-SQIOQPD.
[2023-02-03T11:36:08.889+0530] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=nikheleshbhattacharyya@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Monthly
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2023-02-03T06:05:58.663215+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-03T06:05:58.663215+00:00
[2023-02-03T11:37:58.242+0530] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/root/airflow/dags/Monthly.py", line 478, in extract
    elem = driver.find_element(By.CLASS_NAME,"tablebg")
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".tablebg"}
  (Session info: headless chrome=108.0.5359.124)
Stacktrace:
#0 0x55b9930d22a3 <unknown>
#1 0x55b992e90f77 <unknown>
#2 0x55b992ecd80c <unknown>
#3 0x55b992ecda71 <unknown>
#4 0x55b992f07734 <unknown>
#5 0x55b992eedb5d <unknown>
#6 0x55b992f0547c <unknown>
#7 0x55b992eed903 <unknown>
#8 0x55b992ec0ece <unknown>
#9 0x55b992ec1fde <unknown>
#10 0x55b99312263e <unknown>
#11 0x55b993125b79 <unknown>
#12 0x55b99310889e <unknown>
#13 0x55b993126a83 <unknown>
#14 0x55b9930fb505 <unknown>
#15 0x55b993147ca8 <unknown>
#16 0x55b993147e36 <unknown>
#17 0x55b993163333 <unknown>
#18 0x7f01687d5609 start_thread

[2023-02-03T11:37:58.249+0530] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=Monthly, task_id=extract, execution_date=20230203T060558, start_date=20230203T060608, end_date=20230203T060758
[2023-02-03T11:37:58.271+0530] {standard_task_runner.py:100} ERROR - Failed to execute job 3922 for task extract (Message: no such element: Unable to locate element: {"method":"css selector","selector":".tablebg"}
  (Session info: headless chrome=108.0.5359.124)
Stacktrace:
#0 0x55b9930d22a3 <unknown>
#1 0x55b992e90f77 <unknown>
#2 0x55b992ecd80c <unknown>
#3 0x55b992ecda71 <unknown>
#4 0x55b992f07734 <unknown>
#5 0x55b992eedb5d <unknown>
#6 0x55b992f0547c <unknown>
#7 0x55b992eed903 <unknown>
#8 0x55b992ec0ece <unknown>
#9 0x55b992ec1fde <unknown>
#10 0x55b99312263e <unknown>
#11 0x55b993125b79 <unknown>
#12 0x55b99310889e <unknown>
#13 0x55b993126a83 <unknown>
#14 0x55b9930fb505 <unknown>
#15 0x55b993147ca8 <unknown>
#16 0x55b993147e36 <unknown>
#17 0x55b993163333 <unknown>
#18 0x7f01687d5609 start_thread
; 20037)
[2023-02-03T11:37:58.278+0530] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-03T11:37:58.296+0530] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
