[2023-02-02T05:28:32.664+0530] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: NSE_Open_Interest.extract scheduled__2023-01-28T00:00:00+00:00 [queued]>
[2023-02-02T05:28:32.671+0530] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: NSE_Open_Interest.extract scheduled__2023-01-28T00:00:00+00:00 [queued]>
[2023-02-02T05:28:32.671+0530] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T05:28:32.671+0530] {taskinstance.py:1284} INFO - Starting attempt 3 of 4
[2023-02-02T05:28:32.672+0530] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-02T05:28:32.701+0530] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract> on 2023-01-28 00:00:00+00:00
[2023-02-02T05:28:32.709+0530] {standard_task_runner.py:55} INFO - Started process 6146 to run task
[2023-02-02T05:28:32.715+0530] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'NSE_Open_Interest', 'extract', 'scheduled__2023-01-28T00:00:00+00:00', '--job-id', '3577', '--raw', '--subdir', 'DAGS_FOLDER/NSE_Open_Interest.py', '--cfg-path', '/tmp/tmprsj9ze56']
[2023-02-02T05:28:32.719+0530] {standard_task_runner.py:83} INFO - Job 3577: Subtask extract
[2023-02-02T05:28:32.826+0530] {task_command.py:389} INFO - Running <TaskInstance: NSE_Open_Interest.extract scheduled__2023-01-28T00:00:00+00:00 [running]> on host DESKTOP-SQIOQPD.
[2023-02-02T05:28:32.929+0530] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=nikheleshbhattacharyya@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=NSE_Open_Interest
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2023-01-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-28T00:00:00+00:00
[2023-02-02T05:28:32.931+0530] {logging_mixin.py:137} INFO - 2020-02-14 00:00:00
[2023-02-02T05:28:33.417+0530] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/root/airflow/dags/NSE_Open_Interest.py", line 83, in extract
    dd,values = get_data(date)
TypeError: cannot unpack non-iterable int object
[2023-02-02T05:28:33.422+0530] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=NSE_Open_Interest, task_id=extract, execution_date=20230128T000000, start_date=20230201T235832, end_date=20230201T235833
[2023-02-02T05:28:33.433+0530] {standard_task_runner.py:100} ERROR - Failed to execute job 3577 for task extract (cannot unpack non-iterable int object; 6146)
[2023-02-02T05:28:33.458+0530] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-02T05:28:33.479+0530] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
